[project]
name = "opioid-research-risk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "doubleml>=0.11.2",
    "geopandas>=1.1.1",
    "graphviz>=0.21",
    "matplotlib>=3.10.7",
    "networkx>=3.6.1",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "shap>=0.51.0",
    "tobler>=0.13.0",
    "xgboost>=3.1.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
